### ISSUE TITLE
[bug] Crash at startup only with iOS 11

### ISSUE THREAD

**Issue by maurovanetti** [aaassseee/screen_brightness#11]
### Description (bug summary)

My Flutter app crashes immediately on iOS 11 if I import the plugin in pubspec.yaml, even if I never actually use it.

### Step to reproduce (how to reproduce the bug)
1. Add screen_brightness: ^0.2.2 as a dependency in pubspec.yaml.
2. Make an IPA build.
3. Install on any device with iOS 11.
4. Start the app.
5. The app crashes immediately.

### Platform (Android/iOS/macOS/Windows)

I tested the bug on iPhone 8 using iOS 11.3. The same device model with iOS 12.1 works properly.
I can also replicate the bug on iPhone 6S Plus with iOS 11.4.

(I know it's an old OS, but our app is used by a large demographics and we'd like to support older devices too.)

**Comment by aaassseee** [comment]
Hi, @maurovanetti. Is there any crash log? Or can you try build a screen brightness example app and run it with your iOS 11 device?

**Comment by maurovanetti** [comment]
Hi @aaassseee, thank you for your help.
Unfortunately the log is minimal (find it attached), the app doesn't even start therefore there's no significant Flutter log and the system logs look confusing to me. Consider that I'm testing the app on Browserstack, but they are real devices. The few users with iOS 11 confirm the same problem, but we cannot retrieve any remote log from them for the same reason.
[iphone8-ios11_4-crash.log](https://github.com/aaassseee/screen_brightness/files/9706607/iphone8-ios11_4-crash.log)

**Comment by aaassseee** [comment]
I am also thinking testing my production app with Browserstack. However it is already night here, I may come back after testing.

**Comment by maurovanetti** [comment]
I'm not using Firebase Crashlytics but I can try and find a better log. We're not in a hurry anyway, sleep well. :smile:

**Comment by aaassseee** [comment]
@maurovanetti I had test my app on Browserstack without any issue. Any updates on your side?

**Comment by aaassseee** [comment]
I think your crash issue is not related to the screen_brightness plugin or maybe combine of plugins made it crash. May you show me the library in pubspec which you are currently using?

**Comment by maurovanetti** [comment]
Thank you again. This is interesting because my app breaks only when I add `screen_brightness` to pubspec.yaml, and works again upon removing that line only. But if your test app works properly on iOS 11 the incompatibility must be with something else in the app and not with the OS itself. We should probably close the issue, because in any case the title is misleading.

These are my environment and dependencies:
```
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^3.3.2

dependencies:
  flutter:
    sdk: flutter
  hive_wrapper:
    git:
      url: ssh://git@gitlab.dirittoallostudio.it/desktop-apps/hive-wrapper.git
      ref: v1.2.0
  auto_size_text: ^3.0.0
  barcode_widget: ^2.0.2
  biometric_storage: ^4.1.3
  camera: ^0.10.0
  convert: ^3.0.1
  cryptography: ^2.0.5
  device_info_plus: 4.0.0
  encrypt: ^5.0.1
  flutter_bugfender: ^2.1.0
  flutter_native_splash: ^2.2.5
  http: ^0.13.3
  intl: ^0.17.0
  jwt_decode: ^0.3.1
  logging: ^1.0.1
  logging_appenders: ^1.0.0
  mobile_scanner: ^2.0.0
  otp: ^3.1.1
  package_info_plus: ^1.3.0
  path: ^1.8.1
  path_provider: ^2.0.10
  screen_brightness: ^0.2.2
  sha3: ^0.2.0
  shared_preferences: ^2.0.15
  tuple: ^2.0.0
  url_launcher: ^6.1.5
  version: ^3.0.2
  video_player: ^2.4.2
  wakelock: ^0.6.2
  webview_flutter: ^3.0.4
  yaml: ^3.1.1
```

`hive_wrapper` is a private package with these environment and dependencies:
```
environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_test: ^1.0.1
  path_provider: ^2.0.11
```
