### ISSUE TITLE
[bug] abort() has been callled

### ISSUE THREAD

**Issue by UnluckyY1** [aaassseee/screen_brightness#12]
### Description (bug summary)
adding the plugin to any flutter project will cause a crash on the windows platform
you can find more details in this issue [link](https://github.com/zezo357/flutter_meedu_videoplayer/issues/9) 

### Step to reproduce (how to reproduce the bug)
Simply add   screen_brightness: ^0.2.2 to any flutter windows project and the app will crash immediately

**Comment by aaassseee** [comment]
Hi @UnluckyY1. Thanks for opening the issue. Is that every one crash on start up?

**Comment by aaassseee** [comment]
Hi @UnluckyY1. Can you please try with the fix?
```yaml
dependency_overrides:
  screen_brightness_windows:
    git:
      url: https://github.com/aaassseee/screen_brightness.git
      ref: develop
      path: screen_brightness_windows
```
